export const dummyCategoryList = {
  message: 'ok',
  data: [
    { id: 1, name: 'JavaScript' },
    { id: 2, name: 'Java' },
    { id: 3, name: 'Python' },
    { id: 4, name: 'React' },
    { id: 5, name: 'Angular' },
    { id: 6, name: 'Vue.js' },
    { id: 7, name: 'Node.js' },
    { id: 8, name: 'Spring Boot' },
    { id: 9, name: 'Django' },
    { id: 10, name: 'Express.js' },
    { id: 11, name: 'TypeScript' },
    { id: 12, name: 'HTML/CSS' },
    { id: 13, name: 'SQL' },
    { id: 14, name: 'MSSQL' },
    { id: 15, name: 'Next.js' },
    { id: 16, name: 'REST API' },
    { id: 17, name: 'vanilla-javascript' },
    { id: 18, name: 'ES6' },
    { id: 19, name: 'ES5' },
    { id: 20, name: 'Express' },
    { id: 21, name: 'Mongo DB' },
    { id: 22, name: 'Firebase' },
    { id: 23, name: 'jQuery' },
  ],
};

export const dummyQuestionsList = {
  message: 'ok',
  data: {
    currentPage: 1,
    pageSize: 5,
    totalElements: 100,
    startIndex: 1,
    endIndex: 5,
    hasPreviousPage: false,
    hasNextPage: true,
    data: [
      {
        id: 1,
        content: 'JVM의 역할에 대해 설명해주세요.1',
        likeCount: 1,
        categoryNames: ['JavaScript', 'Java'],
        isLiked: true,
        isBookmarked: false,
      },
      {
        id: 2,
        content: 'JVM의 역할에 대해 설명해주세요.2',
        likeCount: 2,
        categoryNames: ['Python'],
        isLiked: true,
        isBookmarked: true,
      },
      {
        id: 3,
        content: 'JVM의 역할에 대해 설명해주세요.3',
        likeCount: 3,
        categoryNames: ['React'],
        isLiked: false,
        isBookmarked: false,
      },
      {
        id: 4,
        content: 'JVM의 역할에 대해 설명해주세요.4',
        likeCount: 4,
        categoryNames: ['Angular'],
        isLiked: false,
        isBookmarked: true,
      },
      {
        id: 5,
        content: 'JVM의 역할에 대해 설명해주세요.5',
        likeCount: 5,
        categoryNames: ['Vue.js'],
        isLiked: true,
        isBookmarked: false,
      },
      {
        id: 6,
        content: 'JVM의 역할에 대해 설명해주세요.6',
        likeCount: 6,
        categoryNames: ['Node.js'],
        isLiked: true,
        isBookmarked: false,
      },
    ],
  },
};

export const dummyAnswerList = {
  message: 'ok',
  data: {
    currentPage: 1,
    pageSize: 5,
    totalElements: 100,
    startIndex: 1,
    endIndex: 5,
    hasPreviousPage: false,
    hasNextPage: true,
    data: [
      {
        id: 1,
        nickname: 'jjong1',
        content: '좋은 것 입니다1',
        likeCount: 1,
      },
      {
        id: 2,
        nickname: 'jjong2',
        content: '좋은 것 입니다2',
        likeCount: 2,
      },
      {
        id: 3,
        nickname: 'jjong3',
        content: '좋은 것 입니다3',
        likeCount: 3,
      },
      {
        id: 4,
        nickname: 'jjong4',
        content: '좋은 것 입니다4',
        likeCount: 4,
      },
      {
        id: 5,
        nickname: 'jjong5',
        content: '좋은 것 입니다5',
        likeCount: 5,
      },
    ],
  },
};
